# Generated by Django 6.0.2 on 2026-02-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membro_tarefa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
