# Generated by Django 6.0.2 on 2026-02-24 18:40

from django.db import migrations
from django.contrib.auth.hashers import make_password


def criar_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Membro = apps.get_model('core', 'Membro')

    # Only create if admin_clube doesn't already exist
    if not User.objects.filter(username='admin_clube').exists():
        user = User.objects.create(
            username='admin_clube',
            first_name='Administrador',
            email='admin@clubedeprogramacao.com',
            is_active=True,
            password=make_password('Admin@Clube2024'),
        )

        Membro.objects.create(
            usuario=user,
            cargo='administrador',
        )


def reverter_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin_clube').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_solicitacaocadastro'),
    ]

    operations = [
        migrations.RunPython(criar_admin, reverter_admin),
    ]
