# Generated by Django 6.0.2 on 2026-02-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_criar_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocadastro',
            name='senha_plain',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
