# Generated by Django 6.0.2 on 2026-03-03 04:02

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_solicitacaocadastro_senha_plain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('arquivo', 'Arquivo'), ('link', 'Link')], max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='arquivo')),
                ('url', models.URLField(blank=True, default='')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_enviados', to='core.membro')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.tarefa')),
            ],
            options={
                'verbose_name': 'Anexo de Tarefa',
                'verbose_name_plural': 'Anexos de Tarefas',
                'ordering': ['-data_upload'],
            },
        ),
    ]
