# Generated by Django 6.0.2 on 2026-03-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_anexotarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='funcao',
            field=models.CharField(blank=True, choices=[('design', 'Design'), ('desenvolvimento', 'Desenvolvimento'), ('marketing', 'Marketing'), ('gestao', 'Gestão'), ('pesquisa', 'Pesquisa'), ('outro', 'Outro')], default='', max_length=20, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='projeto',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Projeto'),
        ),
    ]
