# Generated by Django 6.0.2 on 2026-03-04 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tarefa_funcao_tarefa_prioridade_tarefa_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocadastro',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='core.setor'),
        ),
    ]
