# Generated by Django 6.0.2 on 2026-03-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_solicitacaocadastro_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocadastro',
            name='cargo',
            field=models.CharField(blank=True, choices=[('presidente', 'Presidente'), ('vice_presidente', 'Vice-Presidente'), ('administrador', 'Administrador'), ('diretor', 'Diretor'), ('antiga_gestao', 'Antiga Gestão'), ('membro', 'Membro')], default='membro', max_length=20),
        ),
    ]
